// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetUserByEmail(ctx context.Context, email string) (User, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
