// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	CategoryID   int32          `json:"category_id"`
	UserID       int32          `json:"user_id"`
	CategoryName string         `json:"category_name"`
	Description  sql.NullString `json:"description"`
	ColorHex     string         `json:"color_hex"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Task struct {
	TaskID       int32          `json:"task_id"`
	CategoryID   int32          `json:"category_id"`
	TaskName     string         `json:"task_name"`
	Description  sql.NullString `json:"description"`
	TimelineType int64          `json:"timeline_type"`
	Priority     string         `json:"priority"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	DueDate      time.Time      `json:"due_date"`
	IsCompleted  sql.NullBool   `json:"is_completed"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type User struct {
	UserID       int32        `json:"user_id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
