name: Task-Manager server CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]


jobs:
  build-and-test:

    name: Test Task-Manager server
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: task_manager
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.23
        id: go


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import Secrets
        uses: hashicorp/vault-action
        with:
          url: https://vault-enterprise.mycompany.com:8200
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          namespace: admin
          secrets: |
            secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;
            secret/data/ci/aws secretKey | AWS_SECRET_ACCESS_KEY ;
            secret/data/ci npm_token

      - name: Retrieve secrets from Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          VAULT_PATH: ${{ secrets.VAULT_PATH }}
        run: |
          echo "Retrieving secrets from Vault..."
          vault kv get -format=json $VAULT_PATH > secrets.json
          export DB_SOURCE=$(jq -r '.data.data.DB_SOURCE' secrets.json)
          export HTTP_SERVER_ADDRESS=$(jq -r '.data.data.HTTP_SERVER_ADDRESS' secrets.json)
          export DB_DRIVER=$(jq -r '.data.data.DB_DRIVER' secrets.json)
          echo "DB_SOURCE=$DB_SOURCE" >> $GITHUB_ENV
          echo "HTTP_SERVER_ADDRESS=$HTTP_SERVER_ADDRESS" >> $GITHUB_ENV
          echo "DB_DRIVER=$DB_DRIVER" >> $GITHUB_ENV

      - name: install golang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout 9m0s --verbose
        
      - name: Run migrations
        run:  make migrateup

      - name: Test
        run:  make test
